// Kaio Fernandes Branco
using AcademiaDoZe.Domain.Entities; using AcademiaDoZe.Domain.Enums; using AcademiaDoZe.Domain.Repositories; using AcademiaDoZe.Domain.ValueObjects; using AcademiaDoZe.Infrastructure.Data; using AcademiaDoZe.Infrastructure.Exceptions; using System.Data; using System.Data.Common;
namespace AcademiaDoZe.Infrastructure.Repositories;
public sealed class ColaboradorRepository : BaseRepository, IColaboradorRepository
{
 const string S="SELECT c.id_colaborador,c.cpf,c.nome,c.nascimento,c.telefone,c.email,c.logradouro_id,c.numero,c.complemento,c.senha,c.foto,c.admissao,c.tipo,c.vinculo,l.id_logradouro,l.cep,l.nome AS logradouro_nome,l.bairro,l.cidade,l.estado,l.pais FROM tb_colaborador c INNER JOIN tb_logradouro l ON c.logradouro_id=l.id_logradouro";
 public ColaboradorRepository(string cs,DatabaseType db):base(cs,db){}
 public Task<Colaborador?> ObterPorId(int id,CancellationToken ct=default)=>One(S+" WHERE c.id_colaborador=@Id",x=>x.AddParameter("@Id",id,DbType.Int32),ct); public Task<IEnumerable<Colaborador>> ObterTodos(CancellationToken ct=default)=>Many(S+" ORDER BY c.nome",null,ct);
 public async Task<Colaborador> Adicionar(Colaborador e,CancellationToken ct=default){const string q="INSERT INTO tb_colaborador (cpf,nome,nascimento,telefone,email,logradouro_id,numero,complemento,senha,foto,admissao,tipo,vinculo) VALUES (@Cpf,@Nome,@Nascimento,@Telefone,@Email,@Logradouro,@Numero,@Complemento,@Senha,@Foto,@Admissao,@Tipo,@Vinculo)";await using var c=await CreateCommandAsync(FormatInsertQuery(q),ct);Add(c,e);return Copy(e,await c.ExecuteScalarIdAsync("ERRO_ADICIONAR_COLABORADOR","Falha ao inserir colaborador.",ct));}
 public async Task<Colaborador> Atualizar(Colaborador e,CancellationToken ct=default){const string q="UPDATE tb_colaborador SET cpf=@Cpf,nome=@Nome,nascimento=@Nascimento,telefone=@Telefone,email=@Email,logradouro_id=@Logradouro,numero=@Numero,complemento=@Complemento,senha=@Senha,foto=@Foto,admissao=@Admissao,tipo=@Tipo,vinculo=@Vinculo WHERE id_colaborador=@Id";await using var c=await CreateCommandAsync(q,ct);Add(c,e);c.AddParameter("@Id",e.Id,DbType.Int32);if(await c.ExecuteNonQueryAsync(ct)==0)throw new InfrastructureException("REGISTRO_NAO_ENCONTRADO","Colaborador não encontrado.");return e;}
 public async Task<bool> Remover(int id,CancellationToken ct=default){await using var c=await CreateCommandAsync("DELETE FROM tb_colaborador WHERE id_colaborador=@Id",ct);c.AddParameter("@Id",id,DbType.Int32);return await c.ExecuteNonQueryAsync(ct)>0;} public Task<Colaborador?> ObterPorCpf(Cpf v,CancellationToken ct=default)=>One(S+" WHERE c.cpf=@V",x=>x.AddParameter("@V",v.Valor,DbType.String),ct); public Task<Colaborador?> ObterPorEmail(Email v,CancellationToken ct=default)=>One(S+" WHERE c.email=@V",x=>x.AddParameter("@V",v.Valor,DbType.String),ct);
 public Task<bool> CpfJaExiste(Cpf v,int? id=null,CancellationToken ct=default)=>Exists("cpf",v.Valor,id,ct); public Task<bool> EmailJaExiste(Email v,int? id=null,CancellationToken ct=default)=>Exists("email",v.Valor,id,ct); public Task<IEnumerable<Colaborador>> ObterPorTipo(ColaboradorTipo v,CancellationToken ct=default)=>Many(S+" WHERE c.tipo=@V",x=>x.AddParameter("@V",(int)v,DbType.Int32),ct); public Task<IEnumerable<Colaborador>> ObterPorVinculo(ColaboradorVinculo v,CancellationToken ct=default)=>Many(S+" WHERE c.vinculo=@V",x=>x.AddParameter("@V",(int)v,DbType.Int32),ct);
 public async Task<bool> TrocarSenha(int id,Senha s,CancellationToken ct=default){await using var c=await CreateCommandAsync("UPDATE tb_colaborador SET senha=@S WHERE id_colaborador=@Id",ct);c.AddParameter("@S",s.Valor,DbType.String);c.AddParameter("@Id",id,DbType.Int32);return await c.ExecuteNonQueryAsync(ct)>0;}
 async Task<bool> Exists(string col,string v,int? id,CancellationToken ct){await using var c=await CreateCommandAsync($"SELECT COUNT(1) FROM tb_colaborador WHERE {col}=@V AND (@Id IS NULL OR id_colaborador<>@Id)",ct);c.AddParameter("@V",v,DbType.String);c.AddParameter("@Id",id,DbType.Int32);return Convert.ToInt32(await c.ExecuteScalarAsync(ct))>0;} static void Add(DbCommand c,Colaborador e){c.AddParameter("@Cpf",e.Cpf.Valor,DbType.String);c.AddParameter("@Nome",e.Nome,DbType.String);c.AddParameter("@Nascimento",e.DataNascimento,DbType.Date);c.AddParameter("@Telefone",e.Telefone.Valor,DbType.String);c.AddParameter("@Email",e.Email.Valor,DbType.String);c.AddParameter("@Logradouro",e.Endereco.Logradouro.Id,DbType.Int32);c.AddParameter("@Numero",e.Endereco.Numero,DbType.String);c.AddParameter("@Complemento",e.Endereco.Complemento,DbType.String);c.AddParameter("@Senha",e.Senha.Valor,DbType.String);c.AddParameter("@Foto",e.Foto.Conteudo,DbType.Binary);c.AddParameter("@Admissao",e.DataAdmissao,DbType.Date);c.AddParameter("@Tipo",(int)e.Tipo,DbType.Int32);c.AddParameter("@Vinculo",(int)e.Vinculo,DbType.Int32);}
 async Task<Colaborador?> One(string q,Action<DbCommand> a,CancellationToken ct){await using var c=await CreateCommandAsync(q,ct);a(c);await using var r=await c.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?Map(r):null;} async Task<IEnumerable<Colaborador>> Many(string q,Action<DbCommand>? a,CancellationToken ct){await using var c=await CreateCommandAsync(q,ct);a?.Invoke(c);await using var r=await c.ExecuteReaderAsync(ct);var z=new List<Colaborador>();while(await r.ReadAsync(ct))z.Add(Map(r));return z;}
 static Colaborador Copy(Colaborador e,int id)=>Colaborador.Criar(id,e.Nome,e.Cpf.Valor,e.DataNascimento,e.Telefone.Valor,e.Email.Valor,e.Endereco.Logradouro,e.Endereco.Numero,e.Endereco.Complemento,e.Senha.Valor,e.Foto,e.DataAdmissao,e.Tipo,e.Vinculo).Value!; static Colaborador Map(DbDataReader r){var l=Logradouro.Criar(r.GetInt32Value("id_logradouro"),r.GetStringValue("cep"),r.GetStringValue("logradouro_nome"),r.GetStringValue("bairro"),r.GetStringValue("cidade"),r.GetStringValue("estado"),r.GetStringValue("pais")).Value!;return Colaborador.Criar(r.GetInt32Value("id_colaborador"),r.GetStringValue("nome"),r.GetStringValue("cpf"),r.GetDateOnlyValue("nascimento"),r.GetStringValue("telefone"),r.GetStringValue("email"),l,r.GetStringValue("numero"),r.GetNullableString("complemento"),r.GetStringValue("senha"),Arquivo.Criar(r.GetNullableBytes("foto")??[]).Value!,r.GetDateOnlyValue("admissao"),(ColaboradorTipo)r.GetInt32Value("tipo"),(ColaboradorVinculo)r.GetInt32Value("vinculo")).Value!;}
}
